### ISSUE TITLE
Install conditionals fails for firmware-linux-free on ubuntu 14.04

### ISSUE THREAD

**Issue by alexgarel** [debops/ansible-apt#23]
I am using debops to install a server on a dell machine.

    "ansible_form_factor": "Rack Mount Chassis"

In [install_conditional.yml](https://github.com/debops/ansible-apt/blob/master/tasks/install_conditional.yml#L6) debops-apt tries to install packages ``firmware-linux-free``, ``firmware-linux-nonfree`` which do not exists !

    $ aptitude search firmware|grep linux
    iuA linux-firmware                  - Firmware for Linux kernel drivers         
    v   linux-firmware:i386             -                                           
    p   linux-firmware-grouper          - Firmware for the Nexus 7 (grouper) tablet.
    p   linux-firmware-nexus7           - Firmware for the Nexus 7 tablet.          
    p   linux-firmware-nonfree          - Non-free firmware for Linux kernel drivers
    p   linux-wlan-ng-firmware          - firmware files used by the linux-wlan-ng d

It seems to be a difference between ubuntu and debian.

How can I solve that the right way ?

I think the condition should be a variable in defaults, which by default is computed but could be overridden.

**Comment by drybjed** [comment]
@alexgarel Good catch! I've never installed Ubuntu on a hardware host, that's why I never had this problem.

I wonder if `install_conditional.yml` is useful, but... I guess it can stay for now. To make it compatible with Ubuntu I would put in `vars/` directory a dict, like:

```
apt_install_firmware:
  'Debian': [ 'firmware-linux-free', 'firmware-linux-nonfree' ]
  'Ubuntu': [ 'linux-firmware', 'linux-firmware-nonfree' ]
```

And then in install conditional we can do something like:

```
apt: name={{ item }} state=installed
with_items: '{{ apt_install_firmware[ansible_distribution] }}'
```

That should do it. I'll add that tommorow, after testing it a bit. Also, Ubuntu packagers: WTF? You just couldn't keep the same name...

**Comment by alexgarel** [comment]
Yep this seems a good solution.
