### ISSUE TITLE
Create seperate apt-cacher-ng role.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-apt#53]
I am working on it.

**Comment by drybjed** [comment]
Great. `apt_cacher_ng__*` should be a good namespace.

**Comment by drybjed** [comment]
@ypid BTW, I have an idea to expose `apt-cacher-ng` behind nginx as for example, `apt-cache.example.org`, do you think that would work? `nginx` would be configured to provide HTTP and HTTPS but without automatic redirection, so that Debian hosts without certificates and `apt-transport-https` would still be able to access the cache.

**Comment by ypid** [comment]
Sounds interesting. I see no reason why this should not work.

**Comment by ypid** [comment]
Role exists by now: https://github.com/debops/ansible-apt_cacher_ng
