### ISSUE TITLE
Wrong apt-sources on Raspbian, kills system

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-apt#9]
When running this role without any configuration on a Raspbian system (Raspbian GNU/Linux 7 (wheezy)), the role installs http://cdn.debian.net as a source.

This is especially fatal, since just a few tasks later ("Install requested packages"), a new version of openssh-server will be installed, which is not able to run. Thus running this role will garbage the whole system.

Possible solution: Try to detect Raspbian and do not set up a source/mirror in this case. Using any of the variables detected by `setup` (esp. `ansible_distribution` is of no help as these all show debian.
Detection can be done by greping for `ID=raspbian` in /etc/os-release.

My knowledge about Ansible is too less, so I can not submit a pull-request. Sorry.

**Comment by ypid** [comment]
Just checking the [role redesign by drybjed](https://github.com/debops/ansible-apt/pull/76). Seems to me this issue might be fixed with the PR. @htgoebel Can you check that and potentially close this issue?

**Comment by drybjed** [comment]
NB: The `debops.core` role can be used to override the distribution/release detection. For example in this case, you would set in your inventory:
```
core__distribution: 'Raspbian'
```
Roles that use the `ansible_local.core.distribution` variable, like `debops.apt` with recent changes, would see "Raspbian" as the distribution instead of "Debian".

Bat-signaling @pedroluislopez to also look at these changes if possible.

**Comment by Vollbrecht** [comment]
There is another option to detect if the System is Debian or Raspian. 
If you youse ansible_lsb fact insted of ansible_distribution you see as ansible_lsb.id = 'Raspian' instead of 'Debian'

here is the example of 2 of my hosts. One is backpord debian and one is fresh installed raspian-lite

`ansible -i ../development.ini pi -m setup -a"filter=ansible_lsb"
192.168.178.59 | SUCCESS => {
    "ansible_facts": {
        "ansible_lsb": {
            "codename": "jessie", 
            "description": "Raspbian GNU/Linux 8.0 (jessie)", 
            "id": "Raspbian", 
            "major_release": "8", 
            "release": "8.0"
        }
    }, 
    `

`ansible -i ../development.ini backup-server -m setup -a"filter=ansible_lsb"
192.168.178.60 | SUCCESS => {
    "ansible_facts": {
        "ansible_lsb": {
            "codename": "jessie", 
            "description": "Debian GNU/Linux 8.8 (jessie)", 
            "id": "Debian", 
            "major_release": "8", 
            "release": "8.8"
        }
    }, 
    "changed": false
}
`
Hope it helps

**Comment by Vollbrecht** [comment]
i createt an pull request for the issue

#91

**Comment by drybjed** [comment]
@Vollbrecht Thanks! This issue should now be fixed in the `debops.apt` `master` branch, therefore I'm closing it. The new role release will be performed at a later date.
